GET http://localhost:8080/reviews/

###
POST http://localhost:8080/reviews
content-type: application/json

{
  "speakerID": "62af5fb317f8d0a3e1fb7d5f",
  "id":"80a3a3f0c07325ccad1e93bd",
  "name":"Neptune",
  "rating":"5",
  "comment":"bad good bad good"
}