
GET  http://localhost:8080/

###

POST http://localhost:8080/speakers/register
content-type: application/json

{
  "userName": "Joyce",
  "userLastname":"Smith",
  "email":"test4@email.com",
  "confirmPassword":"topsecret",
  "password":"topsecret"
}

###
POST  http://localhost:8080/speakers/login
content-type: application/json

{
  "email": "test4@email.com",
  "password":"topsecret"
}

###
GET http://localhost:8080/speakers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicmFuZG9tdXNlciA0IiwiaWQiOiI2MmEzZGE5MTViMGRjODAzZTk2NGEzMjUiLCJpYXQiOjE2NTQ5NjUzODYsImV4cCI6MTY1NzU1NzM4Nn0.BDf_fbQ0HcgzsAiVoKtmZ3tuBYXh63QMUTV8goGfJsE

###
GET http://localhost:8080/speakers/62af5fb317f8d0a3e1fb7d5f